# Generated by Django 3.2.3 on 2021-05-24 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '__first__'),
        ('unit', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('RE', 'Rejected'), ('CO', 'Completed')], default='PE', max_length=2)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit.unit')),
            ],
        ),
    ]
