# Generated by Django 3.2.3 on 2021-05-24 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnitImage',
            new_name='ProductImage',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='unit_set',
            new_name='product',
        ),
    ]
