# Generated by Django 3.2.3 on 2021-05-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
