# Generated by Django 3.2.3 on 2021-05-24 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210524_0424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tag_set',
            new_name='category',
        ),
    ]
