# Generated by Django 3.2.3 on 2021-05-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_tag_set_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='product_image', to='product.Product'),
        ),
    ]
