# Generated by Django 3.2.3 on 2021-05-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('product', '0004_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='category.Category'),
        ),
    ]
