# Generated by Django 3.2.3 on 2021-05-25 07:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='order number')),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='transaction number')),
                ('pay_status', models.CharField(choices=[('TRADE_SUCCESS', 'success'), ('TRADE_CLOSED', 'Timeout off'), ('WAIT_BUYER_PAY', 'Transaction creation'), ('TRADE_FINISHED', 'End of transaction'), ('paying', 'To be paid')], default='paying', max_length=30, verbose_name='Order Status')),
                ('post_script', models.CharField(max_length=200, verbose_name='Order Message')),
                ('order_mount', models.FloatField(default=0.0, verbose_name='order amount')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='Payment time')),
                ('address', models.CharField(default='', max_length=100, verbose_name='Shipping address')),
                ('signer_name', models.CharField(default='', max_length=20, verbose_name='Signature')),
                ('signer_mobile', models.CharField(max_length=11, verbose_name='contact number')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'order',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nums', models.IntegerField(default=0, verbose_name='Number of purchases')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.product', verbose_name='commodity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'shopping cart',
                'verbose_name_plural': 'shopping cart',
            },
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_num', models.IntegerField(default=0, verbose_name='Number of Products')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='cart.orderinfo', verbose_name='order information')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='commodity')),
            ],
            options={
                'verbose_name': 'Order products',
                'verbose_name_plural': 'Order products',
            },
        ),
    ]
