# Generated by Django 3.2.3 on 2021-05-24 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unit', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_units', to='sessions.session')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit.unit')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_units', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
