# Generated by Django 3.2.3 on 2021-05-25 12:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210525_1106'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={},
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='post_script',
            new_name='order_description',
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='order_sn',
            new_name='order_reference',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='pay_status',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='pay_time',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='signer_mobile',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='signer_name',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='trade_no',
        ),
        migrations.RemoveField(
            model_name='orderproducts',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='orderproducts',
            name='products',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='nums',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='products',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='payment_status',
            field=models.CharField(choices=[('TRADE_SUCCESS', 'success'), ('TRADE_CLOSED', 'Timeout off'), ('WAIT_BUYER_PAY', 'Transaction creation'), ('TRADE_FINISHED', 'End of transaction')], default='d', max_length=30, verbose_name='Order Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='pickup_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='product.product', verbose_name='commodity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='cart.orderinfo', verbose_name='order information'),
        ),
        migrations.CreateModel(
            name='ShoppingCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='cart.shoppingcart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.product', verbose_name='commodity')),
            ],
            options={
                'verbose_name': 'shopping cart',
                'verbose_name_plural': 'shopping cart',
            },
        ),
    ]
