# Generated by Django 3.2.3 on 2021-05-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210525_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartitem',
            name='products_num',
            field=models.IntegerField(default=0, verbose_name='Number of Products'),
        ),
    ]
