# Generated by Django 3.2.3 on 2021-05-25 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20210525_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcartitem',
            options={'verbose_name': 'shopping cart Items', 'verbose_name_plural': 'shopping cart Items'},
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='order_description',
        ),
    ]
