# Generated by Django 3.2.3 on 2021-05-25 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20210525_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.shoppingcart', verbose_name='cart'),
        ),
        migrations.DeleteModel(
            name='OrderProducts',
        ),
    ]
