# Generated by Django 3.2.3 on 2021-05-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_orderinfo_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='cart_status',
            field=models.CharField(choices=[('ON_DISPLAY', 'ON_DISPLAY'), ('PROCESSING', 'PROCESSING'), ('PROCESSED', 'PROCESSED')], default='PROCESSING', max_length=30, verbose_name='Cart Status'),
            preserve_default=False,
        ),
    ]
