# Generated by Django 3.2.3 on 2021-06-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_shoppingcart_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='session_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
