# Generated by Django 3.2.3 on 2021-08-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_wishlist'),
    ]

    def update_cart_status(apps, schema_editor):
        record_model = apps.get_model(
            'cart', 'ShoppingCart')

        all_data = record_model.objects.filter(
            cart_status__in=['PROCESSING', 'PROCESSED'])
        all_count = all_data.count()
        total_updated = 0
        if all_count <= 0:
            pass
        else:
            for record in all_data:
                if record.cart_status == 'PROCESSING':
                    record.cart_status = 'ONGOING'
                if record.cart_status == 'PROCESSED':
                    record.cart_status = 'COMPLETE'
                record.save()
                total_updated += 1

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='cart_status',
            field=models.CharField(choices=[('ON_DISPLAY', 'ON_DISPLAY'), ('ONGOING', 'ONGOING'), (
                'COMPLETE', 'COMPLETE')], max_length=30, verbose_name='Cart Status'),
        ),
        migrations.RunPython(update_cart_status),

    ]
