# Generated by Django 3.2.3 on 2021-08-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_alter_shoppingcart_cart_status'),
    ]

    def update_cart_status(apps, schema_editor):
        record_model = apps.get_model(
            'cart', 'OrderInfo')

        all_data = record_model.objects.filter(
            cart__cart_status__in=['ONGOING', 'COMPLETE'])
        all_count = all_data.count()
        total_updated = 0
        if all_count <= 0:
            pass
        else:
            for record in all_data:
                if record.cart.cart_status == 'ONGOING':
                    record.order_status = 'ONGOING'
                if record.cart.cart_status == 'COMPLETE':
                    record.order_status = 'COMPLETE'
                record.save()
                total_updated += 1

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='order_status',
            field=models.CharField(blank=True, choices=[('ONGOING', 'ONGOING'), (
                'COMPLETE', 'COMPLETE')], max_length=30, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='payment_status',
            field=models.CharField(choices=[('TRADE_SUCCESS', 'success'), ('TRADE_CLOSED', 'Timeout off'), (
                'WAIT_BUYER_PAY', 'Transaction creation'), ('TRADE_FINISHED', 'End of transaction')], max_length=30, verbose_name='Payment Status'),
        ),
        migrations.RunPython(update_cart_status),
    ]
