# Generated by Django 3.2.3 on 2021-08-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_auto_20210811_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='card_cvc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='card_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='card_owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='method_of_payment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_mount',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='order amount'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('TRADE_SUCCESS', 'success'), ('TRADE_CLOSED', 'Timeout off'), ('WAIT_BUYER_PAY', 'Transaction creation'), ('TRADE_FINISHED', 'End of transaction')], max_length=30, null=True, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
